# action.yml
name: Patchwork to PR

description: 'Create PR after reading the patch series from the Patchwork URL'

inputs:
  pw_key_str:
    description: kernel or user
    default: "kernel"
  base_branch:
    description: Branch name where the PR is pushed
    default: "workflow"
  github_token:
    description: Secret github token
    required: true
  email_token:
    description: Email token
    required: true
  patchwork_token:
    description: Patchwork token
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    EMAIL_TOKEN: ${{ inputs.email_token }}
    PATCHWORK_TOKEN: ${{ inputs.patchwork_token }}
  args:
    - ${{ inputs.pw_key_str }}
    - ${{ inputs.base_branch }}

branding:
  icon: 'bluetooth'
  color: '#0082FC'
